### ISSUE TITLE
Add `nano` editor, and use it as default editor instead of `vim`

### ISSUE THREAD

**Issue by jkooij** [gavanderhoorn/webvm#1]
Current default editor [is vim](https://github.com/gavanderhoorn/webvm/blob/86d4477e1c55d7d5397d2c98a623ad60ea3c742d/dockerfiles/debian_mini#L16).

I like `vim`, but I can see how not being able to google "how to quit vim" during an exam is frustrating.
Students should be familiar with `nano`

**Comment by gavanderhoorn** [comment]
Resizing still doesn't appear to work correctly, but `nano` is installed and `vim` is no longer the default editor.

See https://github.com/tud-cor/webvm/compare/main...tud-cor:webvm:prod.
